# Generated by Django 4.2.2 on 2023-08-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_description_additionalinformationcollection_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='olfaction',
            old_name='description',
            new_name='content',
        ),
    ]
