# Generated by Django 4.2.3 on 2023-07-19 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField()),
                ('city', models.TextField()),
                ('zip_code', models.TextField()),
                ('altitude', models.TextField()),
                ('longitude', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('image', models.ImageField(upload_to='stores')),
                ('number_products', models.IntegerField(default=0)),
                ('localisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_management.localisation')),
                ('promo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_management.promo')),
            ],
        ),
    ]
