# Generated by Django 4.1.7 on 2023-05-01 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(null=True)),
                ('google', models.URLField(null=True)),
                ('phone', models.CharField(max_length=25)),
                ('gender', models.TextField(choices=[('male', 'male'), ('female', 'female')])),
                ('has_two_factors_authentication', models.BooleanField(default=False)),
                ('number_purchases', models.BigIntegerField(default=0)),
                ('total_sales', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
