# Generated by Django 4.1.7 on 2023-03-28 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='factor_auth_method',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='has_two_factor_authentication',
        ),
    ]
