# Generated by Django 4.1.7 on 2023-04-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_customerprofile_has_two_factors_authentication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='gender',
            field=models.TextField(choices=[('male', 'male'), ('female', 'female')], default='male'),
            preserve_default=False,
        ),
    ]
