# Generated by Django 4.2.2 on 2023-08-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='description',
            new_name='content',
        ),
    ]
