# Generated by Django 4.1.7 on 2023-03-28 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0002_remove_product_brand_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_management.promo'),
        ),
    ]
